trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: cloudtask-secrets

- name: imageName
  value: cloudtask-pro

- name: acrLogin
  value: cloudtaskacr12345.azurecr.io

- name: tag
  value: v1
stages:

# -----------------------
# TERRAFORM STAGE
# -----------------------
- stage: Terraform
  jobs:
  - job: tf
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureRM-Service-Connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd terraform

          terraform init
          terraform validate
          terraform plan
# -----------------------
# BUILD & PUSH IMAGE
# -----------------------
- stage: Build
  displayName: Build & Push Docker Image
  dependsOn: Terraform

  jobs:
  - job: docker
    steps:

    - task: Docker@2
      inputs:
        containerRegistry: ACR-Service-Connection
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: docker/Dockerfile
        buildContext: .
        tags: |
          $(tag)


# -----------------------
# DEPLOY TO VM
# -----------------------
- stage: Deploy
  dependsOn: Build

  jobs:
  - job: deploy
    steps:

    - task: SSH@0
      inputs:
       sshEndpoint: AzureVM-SSH
       runOptions: commands
       commands: |
          set -e

          echo "STEP 1: LOGIN"

          docker login cloudtaskacr12345.azurecr.io -user "$(ACR_USERNAME)" -password "$(ACR_PASSWORD)"

          echo "STEP 2: PULL"

          docker pull cloudtaskacr12345.azurecr.io/cloudtask-pro:v1

          echo "STEP 3: STOP OLD"

          docker stop cloudtask || true
          docker rm cloudtask || true

          echo "STEP 4: RUN"

          docker run -d -p 5000:5000 --restart unless-stopped --name cloudtask cloudtaskacr12345.azurecr.io/cloudtask-pro:v1