trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: cloudtask-pro
  acrLogin: cloudtaskacr12345.azurecr.io
  tag: $(Build.BuildId)

stages:

# -----------------------
# TERRAFORM STAGE
# -----------------------
- stage: Terraform
  jobs:
  - job: tf
    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureRM-Service-Connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |

          echo "Installing Terraform..."

          sudo apt-get update -y
          sudo apt-get install -y wget unzip

          wget https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
          unzip terraform_1.7.5_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

          terraform -version

          echo "Running Terraform..."

          cd terraform

          terraform init
          terraform validate
          terraform plan
# -----------------------
# BUILD & PUSH IMAGE
# -----------------------
- stage: Build
  displayName: Build & Push Docker Image
  dependsOn: Terraform

  jobs:
  - job: docker
    steps:

    - task: Docker@2
      inputs:
        containerRegistry: ACR-Service-Connection
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: Dockerfile
        buildContext: .
        tags: |
          $(tag)


# -----------------------
# DEPLOY TO VM
# -----------------------
- stage: Deploy
  displayName: Deploy to Azure VM
  dependsOn: Build

  jobs:
  - job: deploy
    steps:

    - task: SSH@0
      inputs:
        sshEndpoint: AzureVM-SSH
        runOptions: commands
        commands: |

          echo "Logging into ACR..."

          docker login $(acrLogin) \
            -u $(ACR_USERNAME) \
            -p $(ACR_PASSWORD)

          echo "Pulling image..."

          docker pull $(acrLogin)/$(imageName):$(tag)

          echo "Stopping old container..."

          docker stop cloudtask || true
          docker rm cloudtask || true

          echo "Starting new container..."

          docker run -d -p 5000:5000 --name cloudtask \
            $(acrLogin)/$(imageName):$(tag)